services:
  web:
    image: tomcat:11.0.0-M18
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./target/wacar.war:/usr/local/tomcat/webapps/wacar.war
  
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./src/main/database/wacar.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/db:/var/lib/postgresql/data
      - ./src/main/database/init_db.sql:/init_db.sql
      - ./src/main/database/container_health_check.sh:/container_health_check.sh
    healthcheck:
      test: [ "CMD-SHELL", "/container_health_check.sh"]
      interval: 5s
      timeout: 10s
      retries: 50
    environment:
      - POSTGRES_USER=wacaruser
      - POSTGRES_PASSWORD=wacaruser
      - POSTGRES_DB=wacar_db
